version: '3'
services:
  db:
    image: postgres:12
    env_file:
      - ./data/.env
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:
